# config.yaml


config:
    publicCameraService:
        scheme: "http"
        domain: "192.168.0.140"
        path: "web/ff/cam/web/distributionServer/index.php"
    localService:
        id: "rasp_1"
        serviceName: "raspberry 1"
        cameraName: "camera "
        cameraID: "cam_"
        serviceCameraJoin: "_"



---
# ...