# config.yaml


config:
	publicCameraService:
		scheme: "http"
		domain: "192.168.1.13"
		port: "8000"
		path: "service/registry"
	localService:
		id: "rasp_1"
		serviceName: "raspberry 1"
		cameraName: "camera "
		cameraID: "cam_"
		serviceCameraJoin: "_"


...
# ...